import { Avatar, Badge, Box, Wrap } from "@chakra-ui/core";
import React from "react";
import { theme } from "utils/theme";

const mockMembersList = [
  {
    login: "Ajhaa",
    id: 28290486,
    node_id: "MDQ6VXNlcjI4MjkwNDg2",
    avatar_url: "https://avatars2.githubusercontent.com/u/28290486?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ajhaa",
    html_url: "https://github.com/Ajhaa",
    followers_url: "https://api.github.com/users/Ajhaa/followers",
    following_url: "https://api.github.com/users/Ajhaa/following{/other_user}",
    gists_url: "https://api.github.com/users/Ajhaa/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Ajhaa/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ajhaa/subscriptions",
    organizations_url: "https://api.github.com/users/Ajhaa/orgs",
    repos_url: "https://api.github.com/users/Ajhaa/repos",
    events_url: "https://api.github.com/users/Ajhaa/events{/privacy}",
    received_events_url: "https://api.github.com/users/Ajhaa/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Darake",
    id: 33695190,
    node_id: "MDQ6VXNlcjMzNjk1MTkw",
    avatar_url: "https://avatars1.githubusercontent.com/u/33695190?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Darake",
    html_url: "https://github.com/Darake",
    followers_url: "https://api.github.com/users/Darake/followers",
    following_url: "https://api.github.com/users/Darake/following{/other_user}",
    gists_url: "https://api.github.com/users/Darake/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Darake/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Darake/subscriptions",
    organizations_url: "https://api.github.com/users/Darake/orgs",
    repos_url: "https://api.github.com/users/Darake/repos",
    events_url: "https://api.github.com/users/Darake/events{/privacy}",
    received_events_url: "https://api.github.com/users/Darake/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "esakemp",
    id: 40692959,
    node_id: "MDQ6VXNlcjQwNjkyOTU5",
    avatar_url: "https://avatars3.githubusercontent.com/u/40692959?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/esakemp",
    html_url: "https://github.com/esakemp",
    followers_url: "https://api.github.com/users/esakemp/followers",
    following_url:
      "https://api.github.com/users/esakemp/following{/other_user}",
    gists_url: "https://api.github.com/users/esakemp/gists{/gist_id}",
    starred_url: "https://api.github.com/users/esakemp/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/esakemp/subscriptions",
    organizations_url: "https://api.github.com/users/esakemp/orgs",
    repos_url: "https://api.github.com/users/esakemp/repos",
    events_url: "https://api.github.com/users/esakemp/events{/privacy}",
    received_events_url: "https://api.github.com/users/esakemp/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Granigan",
    id: 28741135,
    node_id: "MDQ6VXNlcjI4NzQxMTM1",
    avatar_url: "https://avatars3.githubusercontent.com/u/28741135?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Granigan",
    html_url: "https://github.com/Granigan",
    followers_url: "https://api.github.com/users/Granigan/followers",
    following_url:
      "https://api.github.com/users/Granigan/following{/other_user}",
    gists_url: "https://api.github.com/users/Granigan/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Granigan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Granigan/subscriptions",
    organizations_url: "https://api.github.com/users/Granigan/orgs",
    repos_url: "https://api.github.com/users/Granigan/repos",
    events_url: "https://api.github.com/users/Granigan/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Granigan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ikuisma",
    id: 21037154,
    node_id: "MDQ6VXNlcjIxMDM3MTU0",
    avatar_url: "https://avatars0.githubusercontent.com/u/21037154?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ikuisma",
    html_url: "https://github.com/ikuisma",
    followers_url: "https://api.github.com/users/ikuisma/followers",
    following_url:
      "https://api.github.com/users/ikuisma/following{/other_user}",
    gists_url: "https://api.github.com/users/ikuisma/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ikuisma/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ikuisma/subscriptions",
    organizations_url: "https://api.github.com/users/ikuisma/orgs",
    repos_url: "https://api.github.com/users/ikuisma/repos",
    events_url: "https://api.github.com/users/ikuisma/events{/privacy}",
    received_events_url: "https://api.github.com/users/ikuisma/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Jakousa",
    id: 6400208,
    node_id: "MDQ6VXNlcjY0MDAyMDg=",
    avatar_url: "https://avatars2.githubusercontent.com/u/6400208?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Jakousa",
    html_url: "https://github.com/Jakousa",
    followers_url: "https://api.github.com/users/Jakousa/followers",
    following_url:
      "https://api.github.com/users/Jakousa/following{/other_user}",
    gists_url: "https://api.github.com/users/Jakousa/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Jakousa/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Jakousa/subscriptions",
    organizations_url: "https://api.github.com/users/Jakousa/orgs",
    repos_url: "https://api.github.com/users/Jakousa/repos",
    events_url: "https://api.github.com/users/Jakousa/events{/privacy}",
    received_events_url: "https://api.github.com/users/Jakousa/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "joonashak",
    id: 18666321,
    node_id: "MDQ6VXNlcjE4NjY2MzIx",
    avatar_url: "https://avatars2.githubusercontent.com/u/18666321?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/joonashak",
    html_url: "https://github.com/joonashak",
    followers_url: "https://api.github.com/users/joonashak/followers",
    following_url:
      "https://api.github.com/users/joonashak/following{/other_user}",
    gists_url: "https://api.github.com/users/joonashak/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/joonashak/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/joonashak/subscriptions",
    organizations_url: "https://api.github.com/users/joonashak/orgs",
    repos_url: "https://api.github.com/users/joonashak/repos",
    events_url: "https://api.github.com/users/joonashak/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/joonashak/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Kaltsoon",
    id: 3078411,
    node_id: "MDQ6VXNlcjMwNzg0MTE=",
    avatar_url: "https://avatars0.githubusercontent.com/u/3078411?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Kaltsoon",
    html_url: "https://github.com/Kaltsoon",
    followers_url: "https://api.github.com/users/Kaltsoon/followers",
    following_url:
      "https://api.github.com/users/Kaltsoon/following{/other_user}",
    gists_url: "https://api.github.com/users/Kaltsoon/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Kaltsoon/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Kaltsoon/subscriptions",
    organizations_url: "https://api.github.com/users/Kaltsoon/orgs",
    repos_url: "https://api.github.com/users/Kaltsoon/repos",
    events_url: "https://api.github.com/users/Kaltsoon/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Kaltsoon/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "markokoskinen2037",
    id: 22393121,
    node_id: "MDQ6VXNlcjIyMzkzMTIx",
    avatar_url: "https://avatars2.githubusercontent.com/u/22393121?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/markokoskinen2037",
    html_url: "https://github.com/markokoskinen2037",
    followers_url: "https://api.github.com/users/markokoskinen2037/followers",
    following_url:
      "https://api.github.com/users/markokoskinen2037/following{/other_user}",
    gists_url: "https://api.github.com/users/markokoskinen2037/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/markokoskinen2037/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/markokoskinen2037/subscriptions",
    organizations_url: "https://api.github.com/users/markokoskinen2037/orgs",
    repos_url: "https://api.github.com/users/markokoskinen2037/repos",
    events_url:
      "https://api.github.com/users/markokoskinen2037/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/markokoskinen2037/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mluukkai",
    id: 523235,
    node_id: "MDQ6VXNlcjUyMzIzNQ==",
    avatar_url: "https://avatars1.githubusercontent.com/u/523235?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mluukkai",
    html_url: "https://github.com/mluukkai",
    followers_url: "https://api.github.com/users/mluukkai/followers",
    following_url:
      "https://api.github.com/users/mluukkai/following{/other_user}",
    gists_url: "https://api.github.com/users/mluukkai/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mluukkai/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mluukkai/subscriptions",
    organizations_url: "https://api.github.com/users/mluukkai/orgs",
    repos_url: "https://api.github.com/users/mluukkai/repos",
    events_url: "https://api.github.com/users/mluukkai/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mluukkai/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Rochet2",
    id: 468816,
    node_id: "MDQ6VXNlcjQ2ODgxNg==",
    avatar_url: "https://avatars0.githubusercontent.com/u/468816?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Rochet2",
    html_url: "https://github.com/Rochet2",
    followers_url: "https://api.github.com/users/Rochet2/followers",
    following_url:
      "https://api.github.com/users/Rochet2/following{/other_user}",
    gists_url: "https://api.github.com/users/Rochet2/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Rochet2/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Rochet2/subscriptions",
    organizations_url: "https://api.github.com/users/Rochet2/orgs",
    repos_url: "https://api.github.com/users/Rochet2/repos",
    events_url: "https://api.github.com/users/Rochet2/events{/privacy}",
    received_events_url: "https://api.github.com/users/Rochet2/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "saarasat",
    id: 43036333,
    node_id: "MDQ6VXNlcjQzMDM2MzMz",
    avatar_url: "https://avatars3.githubusercontent.com/u/43036333?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/saarasat",
    html_url: "https://github.com/saarasat",
    followers_url: "https://api.github.com/users/saarasat/followers",
    following_url:
      "https://api.github.com/users/saarasat/following{/other_user}",
    gists_url: "https://api.github.com/users/saarasat/gists{/gist_id}",
    starred_url: "https://api.github.com/users/saarasat/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/saarasat/subscriptions",
    organizations_url: "https://api.github.com/users/saarasat/orgs",
    repos_url: "https://api.github.com/users/saarasat/repos",
    events_url: "https://api.github.com/users/saarasat/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/saarasat/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sasumaki",
    id: 10545809,
    node_id: "MDQ6VXNlcjEwNTQ1ODA5",
    avatar_url: "https://avatars1.githubusercontent.com/u/10545809?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sasumaki",
    html_url: "https://github.com/sasumaki",
    followers_url: "https://api.github.com/users/sasumaki/followers",
    following_url:
      "https://api.github.com/users/sasumaki/following{/other_user}",
    gists_url: "https://api.github.com/users/sasumaki/gists{/gist_id}",
    starred_url: "https://api.github.com/users/sasumaki/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sasumaki/subscriptions",
    organizations_url: "https://api.github.com/users/sasumaki/orgs",
    repos_url: "https://api.github.com/users/sasumaki/repos",
    events_url: "https://api.github.com/users/sasumaki/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sasumaki/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Sendouc",
    id: 38327916,
    node_id: "MDQ6VXNlcjM4MzI3OTE2",
    avatar_url: "https://avatars3.githubusercontent.com/u/38327916?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Sendouc",
    html_url: "https://github.com/Sendouc",
    followers_url: "https://api.github.com/users/Sendouc/followers",
    following_url:
      "https://api.github.com/users/Sendouc/following{/other_user}",
    gists_url: "https://api.github.com/users/Sendouc/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Sendouc/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Sendouc/subscriptions",
    organizations_url: "https://api.github.com/users/Sendouc/orgs",
    repos_url: "https://api.github.com/users/Sendouc/repos",
    events_url: "https://api.github.com/users/Sendouc/events{/privacy}",
    received_events_url: "https://api.github.com/users/Sendouc/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "totutotu",
    id: 10516652,
    node_id: "MDQ6VXNlcjEwNTE2NjUy",
    avatar_url: "https://avatars2.githubusercontent.com/u/10516652?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/totutotu",
    html_url: "https://github.com/totutotu",
    followers_url: "https://api.github.com/users/totutotu/followers",
    following_url:
      "https://api.github.com/users/totutotu/following{/other_user}",
    gists_url: "https://api.github.com/users/totutotu/gists{/gist_id}",
    starred_url: "https://api.github.com/users/totutotu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/totutotu/subscriptions",
    organizations_url: "https://api.github.com/users/totutotu/orgs",
    repos_url: "https://api.github.com/users/totutotu/repos",
    events_url: "https://api.github.com/users/totutotu/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/totutotu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "vaahtokarkki",
    id: 12064374,
    node_id: "MDQ6VXNlcjEyMDY0Mzc0",
    avatar_url: "https://avatars3.githubusercontent.com/u/12064374?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vaahtokarkki",
    html_url: "https://github.com/vaahtokarkki",
    followers_url: "https://api.github.com/users/vaahtokarkki/followers",
    following_url:
      "https://api.github.com/users/vaahtokarkki/following{/other_user}",
    gists_url: "https://api.github.com/users/vaahtokarkki/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/vaahtokarkki/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/vaahtokarkki/subscriptions",
    organizations_url: "https://api.github.com/users/vaahtokarkki/orgs",
    repos_url: "https://api.github.com/users/vaahtokarkki/repos",
    events_url: "https://api.github.com/users/vaahtokarkki/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/vaahtokarkki/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "woltsu",
    id: 22446801,
    node_id: "MDQ6VXNlcjIyNDQ2ODAx",
    avatar_url: "https://avatars0.githubusercontent.com/u/22446801?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/woltsu",
    html_url: "https://github.com/woltsu",
    followers_url: "https://api.github.com/users/woltsu/followers",
    following_url: "https://api.github.com/users/woltsu/following{/other_user}",
    gists_url: "https://api.github.com/users/woltsu/gists{/gist_id}",
    starred_url: "https://api.github.com/users/woltsu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/woltsu/subscriptions",
    organizations_url: "https://api.github.com/users/woltsu/orgs",
    repos_url: "https://api.github.com/users/woltsu/repos",
    events_url: "https://api.github.com/users/woltsu/events{/privacy}",
    received_events_url: "https://api.github.com/users/woltsu/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "xneme",
    id: 2877177,
    node_id: "MDQ6VXNlcjI4NzcxNzc=",
    avatar_url: "https://avatars2.githubusercontent.com/u/2877177?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/xneme",
    html_url: "https://github.com/xneme",
    followers_url: "https://api.github.com/users/xneme/followers",
    following_url: "https://api.github.com/users/xneme/following{/other_user}",
    gists_url: "https://api.github.com/users/xneme/gists{/gist_id}",
    starred_url: "https://api.github.com/users/xneme/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/xneme/subscriptions",
    organizations_url: "https://api.github.com/users/xneme/orgs",
    repos_url: "https://api.github.com/users/xneme/repos",
    events_url: "https://api.github.com/users/xneme/events{/privacy}",
    received_events_url: "https://api.github.com/users/xneme/received_events",
    type: "User",
    site_admin: false,
  },
];

export const Members = () => {
  return (
    <Wrap>
      #01
      {mockMembersList.map((member, index) => (
        <Box key={member.id} p={1} textAlign="center">
          <Avatar name="Dan Abrahmov" src={member.avatar_url} />
          <Box mt="0.2rem">Kalle</Box>
          <Badge bg={theme.toskaRed} color={theme.backgroundWhite}>
            ALUMNI
          </Badge>
          <Box color={theme.textGrey}>
            #{index < 9 && "0"}
            {index + 1}
          </Box>
        </Box>
      ))}
    </Wrap>
  );
};
